version: '3'

services:
  db:
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: etched
      POSTGRES_DB: etched
    container_name: etched-db
    ports:
      - '5432:5432'
