version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
      - image: postgres:10.6
        environment:
          POSTGRES_PASSWORD: dolphins
          POSTGRES_USER: etched
          POSTGRES_DB: etched

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "backend/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - gradle-dependencies-
            - npm-dependencies-{{ checksum "frontend-ng/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run: ./build.sh

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - save_cache:
          paths:
            - frontend-ng/node_modules
          key: npm-dependencies-{{ checksum "frontend-ng/package-lock.json" }}
