# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker:18.09

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "backend/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - gradle-dependencies-
            - npm-dependencies-{{ checksum "frontend-ng/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run:
          name: Install curl
          command: apk update && apk add curl

      - run:
          name: Install Docker Compose
          # https://circleci.com/docs/2.0/docker-compose/
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            echo "$PATH"
            mv ~/docker-compose /usr/bin/docker-compose

      - run: sh ./build.sh

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - save_cache:
          paths:
            - frontend-ng/node_modules
          key: npm-dependencies-{{ checksum "frontend-ng/package-lock.json" }}
