# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "backend/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - gradle-dependencies-
            - npm-dependencies-{{ checksum "frontend-ng/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run:
          name: Install Docker
          command: |
            # https://discuss.circleci.com/t/how-to-run-docker-build-in-a-circleci-job-that-uses-docker/21075/5
            sudo apt-get update
            sudo apt-get install -y \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg-agent \
                software-properties-common

            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

            sudo add-apt-repository -y \
               "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
               $(lsb_release -cs) \
               stable"

            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

            sudo service docker start

      - run:
          name: Install Docker Compose
          # https://circleci.com/docs/2.0/docker-compose/
          command: |
            set -eu
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run: sh ./build.sh

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-dependencies-{{ checksum "build.gradle" }}

      - save_cache:
          paths:
            - frontend-ng/node_modules
          key: npm-dependencies-{{ checksum "frontend-ng/package-lock.json" }}
