#flyway.locations=db/migration/{vendor}

# Enable to view full http requests
#logging.level.org.apache.http: DEBUG

#logging.level.org.keycloak: DEBUG
logging.pattern.level: '%5p %X{userId}'
#logging.level.org.jooq.tools.LoggerListener: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}:5432/etched
    username: etched
    password: ${DB_PASSWORD}
    platform: postgresql

  jackson:
    serialization:
      # This enables jackson to write Instants as millis since epoch (as an int/long).
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false

  mvc:
    log-resolved-exception:
      # Disables WARN level log for caught exceptions (enabled by default by spring-boot-devtools)
      false

  profiles:
    # Reference the flavor using an environment variable
    active: ${ETCHED_FLAVOR}

  flyway:
    locations:
      - 'classpath:/db/migration'
