com.etchedjournal.auth.cognito.userpoolid: us-east-1_OjrfHbPY4

server:
  ssl:
    key-store: '/etc/letsencrypt/live/etcheddev.com/keystore.p12'
    key-store-password: ${KEYSTORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: etchedapp
  port: 443
logging:
  file: /home/ubuntu/logs/etched-log.log
