#flyway.locations=db/migration/{vendor}

# Enable to view full http requests
#logging.level.org.apache.http: DEBUG

#logging.level.org.keycloak: DEBUG
logging.pattern.level: '%5p %X{userId}'

# https://aws.amazon.com/premiumsupport/knowledge-center/decode-verify-cognito-json-token/
# URL of jwks.json is derived using
# https://cognito-idp.{aws region}.amazonaws.com/{user pool id}/.well-known/jwks.json
com.etchedjournal.auth.jwk.url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_0CjdDf90d/.well-known/jwks.json

spring:
  datasource:
    driver-class-name: org.h2.Driver

#    # Must specify this value in order to execute data-h2.sql.
#    platform: h2
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

  jackson:
    serialization:
      # This enables jackson to write Instants as millis since epoch (as an int/long).
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false

  mvc:
    log-resolved-exception:
      # Disables WARN level log for caught exceptions (enabled by default by spring-boot-devtools)
      false
